tinyMCE.addI18n({zh:{
common:{
edit_confirm:"您要在此大量文字框中使用所見即所得模式嗎？",
apply:"套用",
insert:"新增",
update:"更新",
cancel:"取消",
close:"關閉",
browse:"瀏覽",
class_name:"Class",
not_set:"-- 尚未設置 --",
clipboard_msg:"在 Mozilla 和 Firefox 中無法使用複製或剪下或貼上功能。\n需要更多關於此的訊息嗎？",
clipboard_no_support:"你的瀏覽器目前並不支援，請轉用鍵盤捷徑。",
popup_blocked:"對不起，我們發現你的彈出視窗阻檔器(popup-blocker)已阻檔了一個提供程式功能的視窗。你需要在本網站停用彈出視窗阻檔才能完全運用本工具。",
invalid_data:"錯誤: 輸人了不正確的值，它們被顯示為紅色",
more_colors:"更多顏色"
},
contextmenu:{
align:"對齊",
left:"左邊",
center:"中間",
right:"右邊",
full:"左右對齊"
},
insertdatetime:{
date_fmt:"%Y-%m-%d",
time_fmt:"%H:%M:%S",
insertdate_desc:"插入日期",
inserttime_desc:"插入時間",
months_long:"一月,二月,三月,四月,五月,六月,七月,八月,九月,十月,十一月,十二月",
months_short:"一月,二月,三月,四月,五月,六月,七月,八月,九月,十月,十一月,十二月",
day_long:"星期日,星期一,星期二,星期三,星期四,星期五,星期六,星期日",
day_short:"日,一,二,三,四,五,六,日"
},
print:{
print_desc:"列印"
},
preview:{
preview_desc:"預覽"
},
directionality:{
ltr_desc:"方向由左至右",
rtl_desc:"方向由右至左"
},
layer:{
insertlayer_desc:"插入新圖層",
forward_desc:"移前",
backward_desc:"移後",
absolute_desc:"使用絕對位置",
content:"新圖層..."
},
save:{
save_desc:"儲存",
cancel_desc:"取消所有改變"
},
nonbreaking:{
nonbreaking_desc:"插入空格符號"
},
iespell:{
iespell_desc:"進行串字檢查",
download:"找不到ieSpell. 你想現在安裝嗎？"
},
advhr:{
advhr_desc:"水平分隔線"
},
emotions:{
emotions_desc:"表情符號"
},
searchreplace:{
search_desc:"尋找",
replace_desc:"尋找/取代"
},
advimage:{
image_desc:"插入/編輯圖片"
},
advlink:{
link_desc:"插入/編輯連結"
},
xhtmlxtras:{
cite_desc:"引用",
abbr_desc:"縮寫",
acronym_desc:"首字母縮寫",
del_desc:"刪除",
ins_desc:"插入",
attribs_desc:"插入/編輯屬性"
},
style:{
desc:"編輯CSS樣式"
},
paste:{
paste_text_desc:"貼上純文字",
paste_word_desc:"貼上Word",
selectall_desc:"全選",
plaintext_mode_sticky:"現在是貼上純文字模式，再次點選以切換回一般模式。在您貼上之後您將回到一般的模式。",
plaintext_mode:"現在是貼上純文字模式，再次點選以切換回一般模式。"
},
paste_dlg:{
text_title:"按鍵盤的CTRL + V來將文字貼到視窗中",
text_linebreaks:"保留換行",
word_title:"按鍵盤的CTRL + V來將文字貼到視窗中"
},
table:{
desc:"插入新表格",
row_before_desc:"在前面插入一行",
row_after_desc:"在後面插入一行",
delete_row_desc:"刪除一行",
col_before_desc:"在前面插入一列",
col_after_desc:"在後面插入一列",
delete_col_desc:"移除一列",
split_cells_desc:"分開已合拼的儲存格",
merge_cells_desc:"合拼儲存格",
row_desc:"表格行屬性",
cell_desc:"儲存格屬性",
props_desc:"表格屬性",
paste_row_before_desc:"在前面貼上表格行",
paste_row_after_desc:"在後面貼上表格行",
cut_row_desc:"剪下表格行",
copy_row_desc:"複製表格行",
del:"刪除表格",
row:"行",
col:"列",
cell:"儲存格"
},
autosave:{
unload_msg:"如果你離開本頁，你所作的改變將會失去。",
restore_content:"回復自動儲存的內容",
warning_message:"若您回復自動儲存的內容，將會以上次儲存的內容取代目前所編輯的內容。\n\n確定要回復自動儲存的內容？"
},
fullscreen:{
desc:"切換到全畫面模式"
},
media:{
desc:"插入/編輯內嵌媒體",
edit:"編輯內嵌媒體"
},
fullpage:{
desc:"文件屬性"
},
template:{
desc:"插入預定模板內容"
},
visualchars:{
desc:"啟用/關閉視覺控制字符。"
},
spellchecker:{
desc:"切換拼寫檢查",
menu:"拼寫檢查設定",
ignore_word:"忽略詞",
ignore_words:"忽略全部",
langs:"語言",
wait:"請稍候...",
sug:"建議",
no_sug:"無建議",
no_mpell:"沒有發現拼寫錯誤。"
},
pagebreak:{
desc:"插入分頁符號"
},
advlist:{
types:"類型",
def:"預設",
lower_alpha:"小寫字母",
lower_greek:"小寫希臘字",
lower_roman:"小寫羅馬字",
upper_alpha:"大寫字母",
upper_roman:"大寫羅馬字",
circle:"空心圓",
disc:"實心圓",
square:"正方形"
}}});
