tinyMCE.addI18n('tw_utf8.advanced',{
style_select:"樣式",
font_size:"字體大小",
fontdefault:"字體",
block:"格式",
paragraph:"段落",
div:"Div",
address:"地址：",
pre:"預格式化",
h1:"標題 1",
h2:"標題 2",
h3:"標題 3",
h4:"標題 4",
h5:"標題 5",
h6:"標題 6",
blockquote:"區塊縮排",
code:"代碼",
samp:"代碼樣例",
dt:"定義的名稱",
dd:"定義的描述",
bold_desc:"粗體 (Ctrl / Alt+Shift + B)",
italic_desc:"斜體 (Ctrl / Alt+Shift + I)",
underline_desc:"下劃線",
striketrough_desc:"刪除線 (Alt+Shift+D)",
justifyleft_desc:"左對齊 (Alt+Shift+L)",
justifycenter_desc:"居中對齊 (Alt+Shift+C)",
justifyright_desc:"右對齊 (Alt+Shift+R)",
justifyfull_desc:"拉伸對齊 (Alt+Shift+J)",
bullist_desc:"未排序列表 (Alt+Shift+U)",
numlist_desc:"排序列表 (Alt+Shift+O)",
outdent_desc:"凸排",
indent_desc:"縮排",
undo_desc:"取消 (Ctrl+Z)",
redo_desc:"重做 (Ctrl+Y)",
link_desc:"插入/編輯鏈接 (Alt+Shift+A)",
unlink_desc:"取消鏈接 (Alt+Shift+S)",
image_desc:"插入/編輯圖像 (Alt+Shift+M)",
cleanup_desc:"清理髒亂代碼",
code_desc:"編輯HTML原始碼",
sub_desc:"下標",
sup_desc:"上標",
hr_desc:"插入橫向分隔線",
removeformat_desc:"去除格式",
custom1_desc:"您的自訂說明",
forecolor_desc:"選擇文字顏色",
backcolor_desc:"選擇背景顏色",
charmap_desc:"插入自定義字符",
visualaid_desc:"開關指導/不可見元素",
anchor_desc:"插入/編輯錨點",
cut_desc:"剪下",
copy_desc:"複製",
paste_desc:"貼上",
image_props_desc:"圖像屬性",
newdocument_desc:"新文檔",
help_desc:"幫助",
blockquote_desc:"Blockquote (Alt+Shift+Q)",
clipboard_msg:"複製/剪下/貼上在 Mozilla 和 Firefox中無效。",
path:"路徑",
newdocument:"您確定要清楚所有內容？",
toolbar_focus:"跳到工具按鈕 - Alt+Q，跳到編輯器 - Alt-Z，跳到元素路徑 - Alt-X",
more_colors:"更多顏色",
});
